"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:10:37.362461
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk_catalog_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sla_id', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_catalog_items_category'), 'desk_catalog_items', ['category'], unique=False)
    op.create_index(op.f('ix_desk_catalog_items_code'), 'desk_catalog_items', ['code'], unique=True)
    op.create_table('desk_slas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_slas_priority'), 'desk_slas', ['priority'], unique=False)
    op.create_table('desk_tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=False),
    sa.Column('service_catalog_item_id', sa.String(length=64), nullable=False),
    sa.Column('sla_id', sa.String(length=64), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desk_tickets_priority'), 'desk_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_desk_tickets_requester'), 'desk_tickets', ['requester'], unique=False)
    op.create_index(op.f('ix_desk_tickets_status'), 'desk_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_desk_tickets_title'), 'desk_tickets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desk_tickets_title'), table_name='desk_tickets')
    op.drop_index(op.f('ix_desk_tickets_status'), table_name='desk_tickets')
    op.drop_index(op.f('ix_desk_tickets_requester'), table_name='desk_tickets')
    op.drop_index(op.f('ix_desk_tickets_priority'), table_name='desk_tickets')
    op.drop_table('desk_tickets')
    op.drop_index(op.f('ix_desk_slas_priority'), table_name='desk_slas')
    op.drop_table('desk_slas')
    op.drop_index(op.f('ix_desk_catalog_items_code'), table_name='desk_catalog_items')
    op.drop_index(op.f('ix_desk_catalog_items_category'), table_name='desk_catalog_items')
    op.drop_table('desk_catalog_items')
    # ### end Alembic commands ###
