# ServiceAccount: sm-service-desk
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-service-desk.serviceAccountName" . }}
  labels:
    {{- include "sm-service-desk.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
